name: XcodeBuild

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual dispatch'
        required: false
        default: 'Manual Trigger'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: xcodebuild -project "Dice.xcodeproj" -scheme "Dice" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
